[project]
name = "rabiitmq-practice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aio-pika>=9.5.5",
    "pika>=1.3.2",
    "pydantic-settings>=2.10.1",
]
